spring:
    datasource:
        url: jdbc:mysql://192.168.12.2:3306/springDB?serverTimezone=UTC
        username: root
        password: myensql
    jpa.open-in-view: false

server:
    port: 8080
    address: 127.0.0.1
